#!/bin/bash

echo "Running git pre-commit hook."

echo "Ktlint code format check is starting.."
./gradlew ktlint

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0